### ISSUE TITLE
CellContainer too big.

### ISSUE THREAD

**Issue by AdvancedImagingUTSW** [saalfeldlab/stitching-spark#11]
I ran into the following error when moved to the export step.  Any recommendations?  Thank you...

java.lang.RuntimeException: Number of elements in Container too big, use for example CellContainer instead: 2147483648 > 2147483647

**Comment by igorpisarev** [comment]
Hi @AdvancedImagingUTSW,
I just pushed a fix for this error. Please check out the most recent `master` branch and try running the export step again.

The error is most likely due to the optimization in the exporter code, where it aligns the size of the processing block with the tile size so that the expected number of loads of each tile image is minimized. However, for large tiles (starting at ~1300x1300x1300 px) this indeed exceeds the max possible number of elements in an array. To prevent this, the processing block size is now reduced by half in the longest dimension in case there are too many elements.

**Comment by igorpisarev** [comment]
My first attempt at fixing this had a problem that could led to parts of the export being corrupted.
Another fix has been made: https://github.com/saalfeldlab/stitching-spark/commit/fb1d0fa1e6161480bfbdfd103ef1039dbff4cc37 I tested and it works as expected with large fields of view.
